#!/usr/bin/env bash

#@@@@@@@^^~~~~~~~~~~~~~~~~~~~~^@@@@@@@@@#
#@@@@@@^     ~^  @  @@ @ @ @ I  ~^@@@@@@#
#@@@@@            ~ ~~ ~I          @@@@@#
#@@@@'                  '  _,w@<    @@@@#
#@@@@     @@@@@@@@w___,w@@@@@@@@  @  @@@#
#@@@@     @@@@@@@@@@@@@@@@@@@@@@  I  @@@#
#@@@@     @@@@@@@@@@@@@@@@@@@@*@[ i  @@@#
#@@@@     @@@@@@@@@@@@@@@@@@@@[][ | ]@@@#
#@@@@     ~_,,_ ~@@@@@@@~ ____~ @    @@@#
#@@@@    _~ ,  ,  `@@@~  _  _`@ ]L  J@@@#
#@@@@  , @@w@ww+   @@@ww``,,@w@ ][  @@@@#
#@@@@,  @@@@www@@@ @@@@@@@ww@@@@@[  @@@@#
#@@@@@_|| @@@@@@P' @@P@@@@@@@@@@@[|c@@@@#
#@@@@@@w| '@@P~  P]@@@-~, ~Y@@^'],@@@@@@#
#@@@@@@@[   _        _J@@Tk     ]]@@@@@@#
#@@@@@@@@,@ @@, c,,,,,,,y ,w@@[ ,@@@@@@@#
#@@@@@@@@@ i @w   ====--_@@@@@  @@@@@@@@#
#@@@@@@@@@@`,P~ _ ~^^^^Y@@@@@  @@@@@@@@@#
#@@@@^^=^@@^   ^' ,ww,w@@@@@ _@@@@@@@@@@#
#@@@_xJ~ ~   ,    @@@@@@@P~_@@@@@@@@@@@@#
#@@   @,   ,@@@,_____   _,J@@@@@@@@@@@@@#
#@@L  `' ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#

set -e

ZMAC=$HOME/zmac
DOTS=$ZMAC/dotfiles
SCRIPTS=$ZMAC/scripts
BIN=$HOME/.local/bin
# dotfiles
zshrc=$DOTS/.zshrc
zpro=$DOTS/.zprofile
hush=$DOTS/.hushlogin

# Just a bold yellow arrow
arrow() {
  echo "${yellow}${bold}>>> ${reset}$*"
}

# It's not a trap
. $SCRIPTS/trap.sh

# Create a dotfiles dir and copy files to it
arrow "Creating a directory for dotfiles"
mkdir -p $HOME/.dotfiles && cp -af $zshrc $zpro $hush $_
sleep 1

# Create fresh symlinks to dotfiles in ~/
arrow "Creating symlinks to dotfiles"
for file in $HOME/.dotfiles/.{zshrc,zprofile,hushlogin}; do
    [ -r "$file" ] && [ -f "$file" ] && ln -sf "$file" $HOME;
done;
unset file;
sleep 1

. $SCRIPTS/macdefaults.sh

fortune | cowsay | lolcat
