#!/usr/bin/env bash

#@@@@@@@^^~~~~~~~~~~~~~~~~~~~~^@@@@@@@@@#
#@@@@@@^     ~^  @  @@ @ @ @ I  ~^@@@@@@#
#@@@@@            ~ ~~ ~I          @@@@@#
#@@@@'                  '  _,w@<    @@@@#
#@@@@     @@@@@@@@w___,w@@@@@@@@  @  @@@#
#@@@@     @@@@@@@@@@@@@@@@@@@@@@  I  @@@#
#@@@@     @@@@@@@@@@@@@@@@@@@@*@[ i  @@@#
#@@@@     @@@@@@@@@@@@@@@@@@@@[][ | ]@@@#
#@@@@     ~_,,_ ~@@@@@@@~ ____~ @    @@@#
#@@@@    _~ ,  ,  `@@@~  _  _`@ ]L  J@@@#
#@@@@  , @@w@ww+   @@@ww``,,@w@ ][  @@@@#
#@@@@,  @@@@www@@@ @@@@@@@ww@@@@@[  @@@@#
#@@@@@_|| @@@@@@P' @@P@@@@@@@@@@@[|c@@@@#
#@@@@@@w| '@@P~  P]@@@-~, ~Y@@^'],@@@@@@#
#@@@@@@@[   _        _J@@Tk     ]]@@@@@@#
#@@@@@@@@,@ @@, c,,,,,,,y ,w@@[ ,@@@@@@@#
#@@@@@@@@@ i @w   ====--_@@@@@  @@@@@@@@#
#@@@@@@@@@@`,P~ _ ~^^^^Y@@@@@  @@@@@@@@@#
#@@@@^^=^@@^   ^' ,ww,w@@@@@ _@@@@@@@@@@#
#@@@_xJ~ ~   ,    @@@@@@@P~_@@@@@@@@@@@@#
#@@   @,   ,@@@,_____   _,J@@@@@@@@@@@@@#
#@@L  `' ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#

set -e

ZMAC=$HOME/zmac
ZDOTS=$ZMAC/dotfiles
MAC_DEFS=$ZMAC/scripts/macdefaults.sh
BIN=$HOME/.local/bin
OMZ_CUSTOM=$HOME/.oh-my-zsh/custom
# dotfiles
zpro=$ZDOTS/.zprofile
zshrc=$ZDOTS/.zshrc
aliases=$ZDOTS/.aliases.zsh
hush=$ZDOTS/.hushlogin

# It's not a trap
. $SCRIPTS/trap.sh

# Create a dotfiles dir and copy files to it
echo "Creating a directory for dotfiles"
mkdir -p $HOME/.dotfiles && cp -afi $zpro $zshrc $aliases $_
sleep 1

DOTS=$HOME/.dotfiles

# Create fresh symlinks to dotfiles in ~/
echo "Creating symlinks to dotfiles"
for file in $DOTS/.{zprofile,zshrc}; do
    [ -r "$file" ] && [ -f "$file" ] && ln -sf "$file" $HOME;
done;
unset file;
sleep 1

# Create symlink to aliases in oh-my-zsh custom dir
ln -s $DOTS/.aliases.zsh $OMZ_CUSTOM

# Copy hushfile to ~/
cp -fi  $hush $HOME

. $MAC_DEFS

fortune | cowsay | lolcat
