#!/usr/bin/env zsh

#____________________//Personal sync script for//______________________________#
#______      ______                                           _           _____#
#_____      / ____ \________ _   ______ ___  ____  __________(_)____       ____#
#____      / / __ `/ ___/ _ \ | / / __ `__ \/ __ \/ ___/ ___/ / ___/      _____#
#___      / / /_/ (__  )  __/ |/ / / / / / / /_/ / /  / /  / (__  )      ______#
#____     \ \__,_/____/\___/|___/_/ /_/ /_/\____/_/  /_/  /_/____/      _______#
#_____     \____/                                                      ________#
#______________________________________________________________________________#

                #@@@@@@@^^~~~~~~~~~~~~~~~~~~~~^@@@@@@@@@#
                #@@@@@@^     ~^  @  @@ @ @ @ I  ~^@@@@@@#
                #@@@@@            ~ ~~ ~I          @@@@@#
                #@@@@'                  '  _,w@<    @@@@#
                #@@@@     @@@@@@@@w___,w@@@@@@@@  @  @@@#
                #@@@@     @@@@@@@@@@@@@@@@@@@@@@  I  @@@#
                #@@@@     @@@@@@@@@@@@@@@@@@@@*@[ i  @@@#
                #@@@@     @@@@@@@@@@@@@@@@@@@@[][ | ]@@@#
                #@@@@     ~_,,_ ~@@@@@@@~ ____~ @    @@@#
                #@@@@    _~ ,  ,  `@@@~  _  _`@ ]L  J@@@#
                #@@@@  , @@w@ww+   @@@ww``,,@w@ ][  @@@@#
                #@@@@,  @@@@www@@@ @@@@@@@ww@@@@@[  @@@@#
                #@@@@@_|| @@@@@@P' @@P@@@@@@@@@@@[|c@@@@#
                #@@@@@@w| '@@P~  P]@@@-~, ~Y@@^'],@@@@@@#
                #@@@@@@@[   _        _J@@Tk     ]]@@@@@@#
                #@@@@@@@@,@ @@, c,,,,,,,y ,w@@[ ,@@@@@@@#
                #@@@@@@@@@ i @w   ====--_@@@@@  @@@@@@@@#
                #@@@@@@@@@@`,P~ _ ~^^^^Y@@@@@  @@@@@@@@@#
                #@@@@^^=^@@^   ^' ,ww,w@@@@@ _@@@@@@@@@@#
                #@@@_xJ~ ~   ,    @@@@@@@P~_@@@@@@@@@@@@#
                #@@   @,   ,@@@,_____   _,J@@@@@@@@@@@@@#
                #@@L  `' ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
                #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#

bold=$(tput bold)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Push current directory to Github
pushit() {
  DATE=$(date '+%y%m%d-%H%M')
  git pull 2>&1
  git add . 2>&1
  git commit -m "${DATE}" 2>&1
  git push 2>&1
}

#-------------------------------------------------------------------------------
echo && echo "${yellow}Syncing ~/dotfiles to ~/zmac${reset}" && echo
sleep 1

# sync system dotfiles & backup scriptswith zmac since they should match,
# excluding .git
# Note that this is one-way and I should only ever edit files in ~/.dotfiles
sudo rsync -rtu --exclude '.git' ~/.dotfiles/ ~/zmac/dotfiles/ --progress
sudo rsync -rtu --exclude '.git' ~/.backup-scripts/ ~/zmac/scripts/backup-scripts/ --progress
sleep 1

#-------------------------------------------------------------------------------
# Push repos to Github

echo "" && echo "${yellow}Pushing ~/.dotfiles to Github${reset}"
cd ~/.dotfiles && pushit
sleep 0.5

echo "" && echo "${yellow}Pushing ~/.backup-scripts to Github${reset}"
cd ~/.backup-scripts && pushit
sleep 0.5

echo "" && echo "${yellow}Pushing ~/zmac to Github${reset}"
cd ~/zmac && pushit
sleep 0.5

echo "" && echo "${yellow}Pushing ~/zmac to Github${reset}"
cd ~/zmac && pushit
sleep 0.5

echo "syncall " `date +"%y%m%d %r"` >> ~/Library/Logs/github-repo-backups.log
